#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

shellArgs=()

packageList=$(mktemp)

function echo_debug {
    if [ -v NIX_DEBUG ]; then
        echo "$@" >&2
    fi
}

interpreter=bash # by default in shebang mode
if [ $# -gt 0 ] && [ -x "$1" ]; then
    script="$1"; shift
    echo_debug shebang mode >&2

    while read line; do
        echo_debug hashbang line: $line
        if [ "${line:0:7}" == "prefix=" ]; then
            interpreter="${line:7}"
            continue
        fi
        echo $line >> $packageList
    # https://stackoverflow.com/questions/16854280/a-variable-modified-inside-a-while-loop-is-not-remembered
    done <<< "$(cat "$script" | grep '#!nix-flake-shell' | sed 's;[^ ]* \([^$]\);\1;')"

    read -ra interpreterTokens <<< "$interpreter"
    for interpreterToken in "${interpreterTokens[@]}"; do
        shellArgs+=("$interpreterToken")
    done

    shellArgs+=("$script")

    while [ $# -gt 0 ]; do
        shellArgs+=("$1")
        shift
    done
    echo_debug interpreter: $interpreter

else
    parseShellArgs=0
    while [ $# -gt 0 ]; do
        if [ "$1" == "--" ]; then
            parseShellArgs=1
            shift
            continue
        fi
        if [ "$parseShellArgs" == 0 ]; then
            echo "$1" >> $packageList
        else
            shellArgs+=("$1")
        fi
        shift
    done
fi

echo_debug temporary location: $packageList

echo "with (builtins.getFlake \"$SCRIPT_DIR\");" >> $packageList.nix
echo 'with lib.${builtins.currentSystem};' >> $packageList.nix

cat << EOF >> $packageList.nix
mkWrapper (builtins.filter (x: builtins.typeOf x == "string" && x != "") (builtins.split "\n" (builtins.readFile "$packageList")))
EOF

echo_debug args: ${shellArgs[@]}

nixArgs=()
nixArgs+=(--no-out-link)

if [ -v NIX_DEBUG ]; then
    nixArgs+=(-v)
fi
wrapper="$(nix-build $packageList.nix ${nixArgs[@]})" && $wrapper "${shellArgs[@]}"

echo_debug end
