#!/usr/bin/env bash

set -eu

nixArgs=()

if [ -v NIX_SHOW_TRACE ]; then
    nixArgs+=(--show-trace)
fi

function is_debug_mode {
    [ -v NIX_DEBUG ] || [ -v NFS_VERBOSE ]
}

if is_debug_mode; then
    export NIX_DEBUG NFS_VERBOSE
fi

function echo_debug {
    if is_debug_mode; then
        echo "$@" >&2
    fi
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT="$1"; shift

tmpfile=$(mktemp --dry-run)
echo_debug temp result: $tmpfile

{
    echo "with (builtins.getFlake \"$SCRIPT_DIR\");"
    printf 'let wrapper = lib.${builtins.currentSystem}.mkWrapper "%s";' "$(realpath "$SCRIPT")"
    if is_debug_mode; then
        echo "in wrapper.metadataJSON"
    else
        echo "in wrapper"
    fi
} | nix build -f - -o $tmpfile ${nixArgs[@]}

echo_debug run "$tmpfile" "$SCRIPT" "$@"
if is_debug_mode; then
    cat $tmpfile | jq
else
    "$tmpfile" "$SCRIPT" "$@"
fi

function cleanup {
    is_debug_mode || rm $tmpfile
}

trap cleanup EXIT

